# General settings
listen_addresses = '*'

# Memory settings
shared_buffers = 1GB
effective_cache_size = 2GB
work_mem = 64MB

# Performance settings
fsync = off
full_page_writes = off
synchronous_commit = off
jit = off
checkpoint_timeout = 30min
max_wal_size = 8GB
checkpoint_completion_target = 0.9
autovacuum_naptime = 1h
vacuum_buffer_usage_limit = 8MB

# For SSD storage
random_page_cost = 1.1
effective_io_concurrency = 200

# Logging
log_min_duration_statement = 10ms
log_lock_waits = on

# pg_stat_statements
track_io_timing = on
pg_stat_statements.track = all
