listen_addresses = '*'
fsync = off
full_page_writes = off
jit = off
synchronous_commit = off
checkpoint_timeout = 30min
max_wal_size = 8GB
checkpoint_completion_target = 0.9
shared_buffers = 1GB
autovacuum_naptime = 5s
vacuum_buffer_usage_limit = 8MB
